CREATE TABLE IF NOT EXISTS animal (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    raca VARCHAR(100) NOT NULL,
    dono VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS vacina (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    fabricante VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS vacinacao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    animal_id BIGINT NOT NULL,
    vacina_id BIGINT NOT NULL,
    data_vacinacao DATE NOT NULL,
    responsavel VARCHAR(100) NOT NULL,
    FOREIGN KEY (animal_id) REFERENCES animal(id) ON DELETE CASCADE,
    FOREIGN KEY (vacina_id) REFERENCES vacina(id) ON DELETE CASCADE
);
